"""Add support for SubdomainRescanTarget

Revision ID: 28dbb09fe95f
Revises: d1583004ceac
Create Date: 2021-06-08 13:49:32.079867

"""
from alembic import op
import sqlalchemy as sa
import app.db_models # This is added manually

# revision identifiers, used by Alembic.
revision = '28dbb09fe95f'
down_revision = 'd1583004ceac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subdomainrescan',
    sa.Column('subdomain_scan_target_id', sa.Integer(), nullable=False),
    sa.Column('subdomain_scan_user_id', sa.Integer(), nullable=False),
    sa.Column('subdomain_last_scan', app.db_models.NumericTimestamp(), nullable=True),
    sa.PrimaryKeyConstraint('subdomain_scan_target_id', 'subdomain_scan_user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subdomainrescan')
    # ### end Alembic commands ###
